database:
  uri: "$DB_URI:jdbc:postgresql://localhost:5432/postgres"
  username: "$DB_USER:postgres"
  password: "$DB_PASS:postgres"

ktor:
  application:
    modules:
      - oathbreakers.ApplicationKt.module
  deployment:
    port: "$PORT:8080"
jwt:
  domain: "https://api.oathbreake.rs"
  audience: "rest-api"
  realm: "access_token"
  secret: "$JWT_SECRET:wawawawawa"
