CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, safe_username TEXT NOT NULL, username TEXT NOT NULL, password_hash TEXT NOT NULL);
CREATE INDEX users_safe_username ON users (safe_username);
CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
